# Generated by Django 5.2 on 2025-04-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a trip name', max_length=200)),
                ('start_date', models.DateField(help_text='Enter the trip start date')),
                ('end_date', models.DateField(help_text='Enter the trip end date')),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the trip')),
                ('current_location', models.CharField(help_text='Enter the current location of the trip', max_length=200)),
                ('pickup_location', models.CharField(help_text='Enter the pickup location', max_length=200)),
                ('dropoff_location', models.CharField(help_text='Enter the dropoff location', max_length=200)),
                ('current_cycle_hours', models.FloatField(help_text='Enter the current cycle used (in hours)')),
                ('total_distance', models.FloatField(help_text='Total trip distance in miles')),
                ('fuel_required', models.FloatField(help_text='Fuel required for the trip (in gallons)')),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates if the trip has been completed')),
                ('worked_hours', models.FloatField(default=0, help_text='Total hours worked by the driver')),
                ('fuel_stops', models.IntegerField(default=0, help_text='Number of fuel stops required')),
                ('pickup_dropoff_time', models.FloatField(default=2, help_text='Total time spent on pickup and drop-off (in hours)')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
    ]
