# Generated by Django 5.2 on 2025-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmvdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='fuel_required',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_distance',
            field=models.FloatField(help_text='Total distance of the trip in miles'),
        ),
    ]
