# Generated by Django 5.2 on 2025-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmvdb', '0003_alter_trip_total_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_stops',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_dropoff_time',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='worked_hours',
            field=models.FloatField(default=0),
        ),
    ]
