# Generated by Django 5.2 on 2025-05-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmvdb', '0004_alter_trip_current_cycle_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={},
        ),
    ]
