# Generated by Django 5.2 on 2025-05-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmvdb', '0005_alter_trip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
    ]
