# Generated by Django 5.2 on 2025-05-06 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmvdb', '0006_alter_trip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
